// Parity test: JS pushActionToken must produce the same packed state as
// Python's push_action_token_packed in src/gpu_poker/policy_transformer.py.
//
// Golden values were generated by running this snippet (see
// tests/golden/pushtoken_golden.py for the source):
//
//   actions = [
//     (player_id=0, action_type=2, raise_bucket=0, stage=0),  # call PRE
//     (player_id=1, action_type=3, raise_bucket=4, stage=1),  # raise FLOP b4
//     (player_id=0, action_type=0, raise_bucket=0, stage=1),  # fold
//   ]
//   -> first 16 floats of packed state: [1,3,1,1, 2,4,5,2, 1,1,1,2, 0,0,0,0]
//   -> length field (slot 128):         3

import { test } from "node:test";
import { strict as assert } from "node:assert";
import { pushActionToken } from "../src/inference.mjs";

const STATE_WIDTH = 32 * 4 + 1;

test("pushActionToken parity with Python push_action_token_packed", () => {
  let h = new Float32Array(STATE_WIDTH);
  const actions = [
    { playerId: 0, actionType: 2, raiseBucket: 0, stage: 0 },
    { playerId: 1, actionType: 3, raiseBucket: 4, stage: 1 },
    { playerId: 0, actionType: 0, raiseBucket: 0, stage: 1 },
  ];
  for (const a of actions) h = pushActionToken(h, a);

  const expectedHead = [1, 3, 1, 1, 2, 4, 5, 2, 1, 1, 1, 2, 0, 0, 0, 0];
  for (let i = 0; i < expectedHead.length; i++) {
    assert.equal(
      h[i],
      expectedHead[i],
      `slot ${i}: expected ${expectedHead[i]}, got ${h[i]}`,
    );
  }
  assert.equal(h[STATE_WIDTH - 1], 3, "length field should be 3 after 3 pushes");
});

test("pushActionToken: length cap at MAX_TOKENS=32", () => {
  let h = new Float32Array(STATE_WIDTH);
  // Push 35 actions; only 32 should land.
  for (let i = 0; i < 35; i++) {
    h = pushActionToken(h, {
      playerId: i % 2,
      actionType: 1,
      raiseBucket: 0,
      stage: 0,
    });
  }
  assert.equal(h[STATE_WIDTH - 1], 32, "length must cap at MAX_TOKENS=32");
});

test("pushActionToken: empty state init -> length 0, all zeros", () => {
  const h = new Float32Array(STATE_WIDTH);
  assert.equal(h[STATE_WIDTH - 1], 0);
  for (let i = 0; i < STATE_WIDTH; i++) assert.equal(h[i], 0);
});

test("pushActionToken: rejects wrong-size buffer", () => {
  assert.throws(
    () =>
      pushActionToken(new Float32Array(10), {
        playerId: 0,
        actionType: 0,
        raiseBucket: 0,
        stage: 0,
      }),
    /expected state length/,
  );
});
